### ISSUE TITLE
SQLite Syntax Error

### ISSUE THREAD

**Issue by MattBDev** [PlotMasterSuite/PlotMaster#6]
`AUTO_INCREMENT` is invalid syntax for SQLite and will not create the tables.

**Comment by Double0negative** [comment]
Haven't got around to fixing this yet. 

Reference 

https://github.com/PlotMasterSuite/PlotMaster/commit/8de2bdcda544e0da154a6b072c0d61153b219a87

**Comment by MattBDev** [comment]
It sounded like you were going to release the plugin in the last commit so I just wanted to remind you :wink:

**Comment by Double0negative** [comment]
Not quite, that commit was just meaning it is able to startup now xD, still got a long way to go

**Comment by Double0negative** [comment]
https://github.com/PlotMasterSuite/PlotMaster/commit/8eeb0e509f57221e548636ff717a077104e33553

Fixes this :)

**Comment by drtshock** [comment]
rekt

**Comment by MattBDev** [comment]
Okay?
